/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ERC677Receiver } from "./ERC677Receiver";

export class ERC677ReceiverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ERC677Receiver {
    return new Contract(address, _abi, signerOrProvider) as ERC677Receiver;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "_sender",
        type: "address"
      },
      {
        name: "_value",
        type: "uint256"
      },
      {
        name: "_data",
        type: "bytes"
      }
    ],
    name: "onTokenTransfer",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function"
  }
];
