/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PointerInterfaceInterface extends Interface {
  functions: {
    getAddress: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class PointerInterface extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PointerInterface;
  attach(addressOrName: string): PointerInterface;
  deployed(): Promise<PointerInterface>;

  on(event: EventFilter | string, listener: Listener): PointerInterface;
  once(event: EventFilter | string, listener: Listener): PointerInterface;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): PointerInterface;
  removeAllListeners(eventName: EventFilter | string): PointerInterface;
  removeListener(eventName: any, listener: Listener): PointerInterface;

  interface: PointerInterfaceInterface;

  functions: {
    getAddress(): Promise<string>;
  };

  getAddress(): Promise<string>;

  filters: {};

  estimate: {
    getAddress(): Promise<BigNumber>;
  };
}
