/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { AccessControllerInterface } from "./AccessControllerInterface";

export class AccessControllerInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AccessControllerInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as AccessControllerInterface;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address"
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes"
      }
    ],
    name: "hasAccess",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
