/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { ENSResolver } from "./ENSResolver";

export class ENSResolverFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ENSResolver {
    return new Contract(address, _abi, signerOrProvider) as ENSResolver;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "node",
        type: "bytes32"
      }
    ],
    name: "addr",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
