/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, Signer } from "ethers";
import { Provider } from "ethers/providers";

import { PointerInterface } from "./PointerInterface";

export class PointerInterfaceFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PointerInterface {
    return new Contract(address, _abi, signerOrProvider) as PointerInterface;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getAddress",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];
